const SUPABASE_URL = "https://gpajaajgjqjfmqkgkccv.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwYWphYWpnanFqZm1xa2drY2N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MzYyNTUsImV4cCI6MjA2NjAxMjI1NX0.kMRIatwFV6BgFADJccakiabah3zszCWYxB6sZMSggp8";
const client = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
